/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CcBack: typeof import('./src/components/cc/Back.vue')['default']
    ChartsBarBasic: typeof import('./src/components/charts/BarBasic.vue')['default']
    ChartsLineBasic: typeof import('./src/components/charts/LineBasic.vue')['default']
    ChartsLineStacked: typeof import('./src/components/charts/LineStacked.vue')['default']
    ChartsPieBasic: typeof import('./src/components/charts/PieBasic.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    IconSvg: typeof import('./src/components/icon/svg.vue')['default']
    ReDateQuick: typeof import('./src/components/re/DateQuick.vue')['default']
    ReFileUpload: typeof import('./src/components/re/FileUpload.vue')['default']
    RePagination: typeof import('./src/components/re/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
