// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
	export interface GlobalComponents {
		ElAffix: typeof import("element-plus/es")["ElAffix"];
		ElAside: typeof import("element-plus/es")["ElAside"];
		ElBacktop: typeof import("element-plus/es")["ElBacktop"];
		ElBreadcrumb: typeof import("element-plus/es")["ElBreadcrumb"];
		ElBreadcrumbItem: typeof import("element-plus/es")["ElBreadcrumbItem"];
		ElButton: typeof import("element-plus/es")["ElButton"];
		ElCol: typeof import("element-plus/es")["ElCol"];
		ElConfigProvider: typeof import("element-plus/es")["ElConfigProvider"];
		ElContainer: typeof import("element-plus/es")["ElContainer"];
		ElDrawer: typeof import("element-plus/es")["ElDrawer"];
		ElDropdown: typeof import("element-plus/es")["ElDropdown"];
		ElDropdownItem: typeof import("element-plus/es")["ElDropdownItem"];
		ElDropdownMenu: typeof import("element-plus/es")["ElDropdownMenu"];
		ElFooter: typeof import("element-plus/es")["ElFooter"];
		ElHeader: typeof import("element-plus/es")["ElHeader"];
		ElIcon: typeof import("element-plus/es")["ElIcon"];
		ElImage: typeof import("element-plus/es")["ElImage"];
		ElLink: typeof import("element-plus/es")["ElLink"];
		ElMain: typeof import("element-plus/es")["ElMain"];
		ElMenu: typeof import("element-plus/es")["ElMenu"];
		ElMenuItem: typeof import("element-plus/es")["ElMenuItem"];
		ElMenuItemGroup: typeof import("element-plus/es")["ElMenuItemGroup"];
		ElRow: typeof import("element-plus/es")["ElRow"];
		ElScrollbar: typeof import("element-plus/es")["ElScrollbar"];
		ElSubMenu: typeof import("element-plus/es")["ElSubMenu"];
		ElTooltip: typeof import("element-plus/es")["ElTooltip"];
		HelloWorld: typeof import("./src/components/HelloWorld.vue")["default"];
		IconIfy: typeof import("./src/components/re-icon/IconIfy.vue")["default"];
		Index: typeof import("./src/components/Svg/Index.vue")["default"];
		RouterLink: typeof import("vue-router")["RouterLink"];
		RouterView: typeof import("vue-router")["RouterView"];
	}
}
